{
  "openapi": "3.0.0",
  "info": {
    "title": "Backup",
    "description": "Backup API documentation",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/backup/status": {
      "get": {
        "tags": [
          "General"
        ],
        "summary": "Returns informations about created backup, default configuration",
        "responses": {
          "200": {
            "$ref": "#/components/responses/200backup"
          }
        }
      },
      "x-web": {
        "menu": [
          "System",
          "Maintenance",
          "Backup"
        ]
      },
      "parameters": []
    },
    "/backup/actions/create_default": {
      "post": {
        "tags": [
          "General"
        ],
        "summary": "Creates default configuration",
        "responses": {
          "200": {
            "$ref": "#/components/responses/200backup_defaults"
          },
          "422": {
            "$ref": "#/components/responses/422response"
          }
        }
      },
      "x-web": {
        "menu": [
          "System",
          "Maintenance",
          "Backup"
        ]
      }
    },
    "/backup/actions/remove_default": {
      "post": {
        "tags": [
          "General"
        ],
        "summary": "Removes default configuration",
        "responses": {
          "200": {
            "$ref": "#/components/responses/200backup_defaults"
          }
        }
      },
      "x-web": {
        "menu": [
          "System",
          "Maintenance",
          "Backup"
        ]
      }
    },
    "/backup/actions/generate": {
      "post": {
        "tags": [
          "General"
        ],
        "summary": "Generates backup configuration to download",
        "responses": {
          "200": {
            "$ref": "#/components/responses/200backup_checksums"
          },
          "422": {
            "$ref": "#/components/responses/422response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "$ref": "#/components/schemas/req_encrypt_info"
                  }
                }
              }
            }
          }
        }
      },
      "x-web": {
        "menu": [
          "System",
          "Maintenance",
          "Backup"
        ]
      }
    },
    "/backup/actions/download": {
      "post": {
        "tags": [
          "General"
        ],
        "summary": "Downloads generated backup file",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/x-targz": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              },
              "application/x-7z-compressed": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404backup_doesnt_exist"
          }
        }
      },
      "x-web": {
        "menu": [
          "System",
          "Maintenance",
          "Backup"
        ]
      }
    },
    "/backup/actions/upload": {
      "post": {
        "tags": [
          "General"
        ],
        "summary": "Uploads backup into device to apply",
        "responses": {
          "200": {
            "$ref": "#/components/responses/200backup_checksums"
          },
          "422": {
            "$ref": "#/components/responses/422response"
          }
        },
        "description": "Upload backup file.",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "encrypt": {
                    "type": "string",
                    "description": "Specifies if backup is encrypted.",
                    "x-web": {
                      "pretty": "Encrypt",
                      "input-type": "switch"
                    },
                    "enum": [
                      "0",
                      "1"
                    ]
                  },
                  "password": {
                    "type": "string",
                    "x-web": {
                      "pretty": "Password",
                      "input-type": "input"
                    },
                    "description": "Password for encrypted archive."
                  },
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        }
      },
      "x-web": {
        "menu": [
          "System",
          "Maintenance",
          "Backup"
        ]
      }
    },
    "/backup/actions/delete": {
      "post": {
        "tags": [
          "General"
        ],
        "summary": "Removes backup file from device",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "sha256": {
                          "type": "string"
                        },
                        "md5": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "x-examples": {
                    "example-1": {
                      "success": true,
                      "data": {
                        "sha256": "-",
                        "md5": "-"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "success": true,
                      "data": {
                        "sha256": "-",
                        "md5": "-"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404backup_doesnt_exist"
          }
        }
      },
      "x-web": {
        "menu": [
          "System",
          "Maintenance",
          "Backup"
        ]
      }
    },
    "/backup/actions/apply": {
      "post": {
        "tags": [
          "General"
        ],
        "summary": "Applies backup from backup file",
        "responses": {
          "200": {
            "$ref": "#/components/responses/200backup_apply"
          },
          "422": {
            "$ref": "#/components/responses/422response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "$ref": "#/components/schemas/req_encrypt_info"
                  }
                }
              }
            }
          }
        }
      },
      "x-web": {
        "menu": [
          "System",
          "Maintenance",
          "Backup"
        ]
      }
    },
    "/backup/actions/reset_settings": {
      "post": {
        "summary": "Resets device configuration",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "$ref": "#/components/schemas/reset_settings"
                  }
                }
              }
            }
          }
        },
        "tags": ["General"],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "description": "Operation status"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "lan_ip": {
                          "type": "string",
                          "description": "Default IP address of the device when resetting to user defaults."
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "422": {
            "$ref": "#/components/responses/422response"
          }
        }
      },
      "x-web": {
        "menu": [
          "System",
          "Maintenance",
          "Backup"
        ]
      }
    }
  },
  "components": {
    "responses": {
      "200backup": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "description": "Operation status"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "date": {
                      "type": "string",
                      "description": "Date of user created default backup."
                    },
                    "sha256": {
                      "type": "string",
                      "description": "SHA256 Hash of created backup."
                    },
                    "md5": {
                      "type": "string",
                      "description": "MD5 Hash of created backup."
                    }
                  }
                }
              }
            },
            "examples": {
              "example-1": {
                "value": {
                  "success": true,
                  "data": {
                    "date": "-",
                    "sha256": "8db04d9cbbca782da064942b95442d774b56f5a67f180578419a3ceb0cfd2378",
                    "md5": "abb33e3ebd43b3e91faa3468c919b9f0"
                  }
                }
              }
            }
          }
        }
      },
      "200backup_defaults": {
        "description": "Returns data object",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "description": "Operation status"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "date": {
                      "type": "string",
                      "description": "Date of user created default backup."
                    }
                  }
                }
              }
            }
          }
        }
      },
      "200backup_apply": {
        "description": "Returns data object",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "lan_ipv4": {
                      "type": "string",
                      "description": "LAN IPv4 IP address after backup apply.",
                      "default": "192.168.1.2"
                    },
                    "lan_ipv6": {
                      "type": "string",
                      "description": "LAN IPv6 IP address after backup apply.",
                      "default": "fd3b:de7b:3f52::1"
                    },
                    "http_port": {
                      "type": "string",
                      "description": "WebUI HTTP port, if HTTP access is enabled.",
                      "default": "80"
                    },
                    "https_port": {
                      "type": "string",
                      "description": "WebUI HTTPS port, if HTTPS access is enabled.",
                      "default": "443"
                    }
                  }
                }
              }
            },
            "examples": {
              "example-1": {
                "value": {
                  "success": true,
                  "data": {
                    "response": "string"
                  }
                }
              }
            }
          }
        }
      },
      "200backup_checksums": {
        "description": "Returns data object",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "sha256": {
                      "type": "string",
                      "description": "SHA256 Hash of created backup."
                    },
                    "md5": {
                      "type": "string",
                      "description": "MD5 Hash of created backup."
                    }
                  }
                }
              }
            },
            "examples": {
              "example-1": {
                "value": {
                  "success": true,
                  "data": {
                    "sha256": "ff2b409ff05609579c8df9c8bbc66e7ea1bf5eff8e33ffa5d1e386163f5a9463",
                    "md5": "de22c665398d350aa7800a039ae5f9e2"
                  }
                }
              }
            }
          }
        }
      },
      "file_download": {
        "description": "Success",
        "content": {
          "application/octet-stream": {
            "schema": {
              "type": "string",
              "format": "binary"
            }
          }
        }
      },
      "404backup_doesnt_exist": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "errors": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "source": {
                        "type": "string"
                      },
                      "error": {
                        "type": "string"
                      },
                      "code": {
                        "type": "integer"
                      }
                    }
                  }
                }
              },
              "x-examples": {
                "example-1": {
                  "success": false,
                  "errors": [
                    {
                      "source": "Request",
                      "error": "Backup not found.",
                      "code": 122
                    }
                  ]
                }
              }
            },
            "examples": {
              "example-1": {
                "value": {
                  "success": true,
                  "errors": [
                    {
                      "source": "Request.",
                      "error": "Backup not found.",
                      "code": 122
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "requestBodies": {},
    "schemas": {
      "req_encrypt_info": {
        "title": "req_encrypt_info",
        "type": "object",
        "properties": {
          "encrypt": {
            "type": "string",
            "description": "Specifies if backup is encrypted.",
            "x-web": {
              "pretty": "Encrypt",
              "input-type": "switch"
            },
            "enum": [
              "0",
              "1"
            ]
          },
          "password": {
            "type": "string",
            "x-web": {
              "pretty": "Password",
              "input-type": "input"
            },
            "description": "Password for encrypted archive."
          }
        }
      },
      "reset_settings": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": ["system", "factory", "user"],
            "description": "Type of reset that will happen.",
            "x-web": {
              "pretty": "Type",
              "input-type": "select",
              "enum-pretty": {
                "system": "System settings",
                "factory": "Factory defaults",
                "user": "User's default configuration"
              }
            }
          }
        },
        "required": ["type"]
      }
    }
  }
}
